<a href="https://colab.research.google.com/github/seungukkim/R_lecture/blob/main/day0628.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 반복문 복습
- for loop and while loop

In [9]:
a = "Kaggle"

for i in a:
  if i=="a":
    break;
  

- 리스트

In [11]:
numbers = [1,2,3,4,5]
sum=0

for num in numbers:
  sum+=num

print(sum)

15


In [12]:
fruits=['apple','kiwi', 'mango']
newlist =[]

for fruit in fruits:
  if "a" in fruit:
    newlist.append(fruit)

print(newlist)

['apple', 'mango']


In [13]:
a=[1,2,3]
b=a
b[1]=9
print(a)
print(b)

[1, 9, 3]
[1, 9, 3]


## 사용자 정의 함수
- 내가 필요에 의해 직접 함수를 작성



In [15]:
def 함수명(param1, param2):
  #코드
  return None

In [28]:
def add(a=0,b=1):
  """a,b를 더하는 함수
  
  Parameters:
  a(int): int형 숫자 a입력
  b(int): int형 숫자 b입력

  return:
    int:반환값

  """
  c=a+b
  return c

print(add(5,4))
print(add.__doc__)

9
a,b를 더하는 함수
  
  Parameters:
  a(int): int형 숫자 a입력
  b(int): int형 숫자 b입력

  return:
    int:반환값

  


In [21]:
def add(a,b):
  c=a+b
  return c

def minus(a,b):
  c=a-b
  return c


def multi(a,b):
  c=a*b
  return c


def divide(a,b):
  c=a/b
  return c

print(add(4,5))
print(minus(4,5))
print(multi(4,5))
print(divide(4,5))


9
-1
20
0.8


## 여러개의 변수를 받을 때

In [134]:
def add_many(*args):
  result = 0
  for i in args:
    result = result +i
    print(type(result))
  return result
  

add_many(1,2,3,4,5,5,6,8,89)

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


123

In [26]:
a=1
def vartest(a):
  a+=1
  return a

a=vartest(a)
print(a)

2


In [27]:
a=1
def vartest():
  global a
  a = a+1

vartest()
print(a)

2


- 함수 문서화
    + 키워드: Docstinrg

In [32]:
class Calculator:
  def __init__self(self):
    self.result =0

  def add(self, num):
    self.result += num
    return self. result

  

In [38]:
import numpy as np

A=[1,2,3]
B=[4,5,6]

np_A = np.array(A)
np_B = np.array(B)

np_A / np_B ** 2

array([0.0625    , 0.08      , 0.08333333])

## NumPy
- 내장모듈(=라이브러리 = 패키지)(X)
- 별도 라이브러리 설치

In [40]:
import numpy as np
print(np.__version__)

1.21.6


In [41]:
temp=[1,2,3]
temp_array = np.array(temp)

print(type(temp))
print(type(temp_array)) # 배열로 변환이 되었다는 것을 의미한다.

<class 'list'>
<class 'numpy.ndarray'>


In [48]:
math_score=[90,80,100]
eng_score=[80,90,100]

print(math_score + eng_score)
np_math = np.array(math_score)
np_eng = np.array(eng_score)
total = np_math + np_eng
print(total)
print(type(total))

[90, 80, 100, 80, 90, 100]
[170 170 200]
<class 'numpy.ndarray'>


## 집계 함수

In [52]:
print(np.min(total))
print(np.max(total))
print(np.sum(total))

170
200
540


## 차원
- 배열의 차원 확인 필요


In [55]:
# 1차원 배열
temp_arr = np.array([1,2,3])
print(temp_arr.shape) #값이 3개
print(temp_arr.ndim) #1차원

(3,)
1


In [58]:
# 2차원 배열
temp_arr=np.array([[1,2,3],[4,5,6]])
print(temp_arr.shape) #2*3배열
print(temp_arr.ndim) #2차원
print(temp_arr)

(2, 3)
2
[[1 2 3]
 [4 5 6]]


In [60]:
# 3차원 배열 -> 이미지
temp_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)

(2, 2, 3)
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 배열 생성의 다양한 방법들
- 모두 0으로 채운다

In [2]:
import numpy as np
print(np.__version__)

1.21.6


In [7]:
temp_arr= np.zeros((2,3))
temp_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

- 모두 1로 채운다

In [8]:
temp_arr = np.ones((2,3))
temp_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

- 임의의 상수값으로 채운다

In [10]:
temp_arr = np.full((3,3),5)
temp_arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

- 최소, 최대 숫자의 범위를 정해두고, 각구간별로 값을 생성

In [11]:
temp_arr = np.linspace(5,10,10)
temp_arr

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

- 반복문 시 , 자주 등장하는 배

In [15]:
temp_arr = np.arange(1,11,1)
temp_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 난수 생성

In [19]:
from numpy import random
x=random.rand()
print(x)

0.4197892844762233


In [20]:
import numpy
x= numpy.random.rand()
print(x)

0.8489952461394101


## 랜덤 정수값 추

In [25]:
from numpy import random
x= random.randint(100, size=(90))
print(x)

[65 20 95 55 13 39 19 56  8 26 44 23 59  6 32 97 87 18 42 55 28 98  2 69
 68  8 58 20  8 76  4 68  6 97 42 83 34 92 10 16 59 79 57 16 41 75 65 51
 99 54 88 17 94 50  1 83 37 64 78 72 50 93 64 84 36 40 98 99 11 66 39 54
 43 65 38 31 98 36 35 71 78 11  1 99 57 87 47 50 25 53]


## 랜덤 배열 ,실수

In [29]:
from numpy import random
x = random.rand(2,5)
print(x)
type(x)

[[0.10636109 0.39654714 0.98230141 0.68008412 0.45948323]
 [0.02152314 0.53716145 0.87837662 0.02882575 0.8048422 ]]


numpy.ndarray

## numpy 사칙 연

In [31]:
import numpy as np
array_01 = np.array([1,2,3])
array_02 = np.array([10,20,30])


In [36]:
newArr = np.add(array_01,array_02)
print(newArr)
newArr = np.subtract(array_01,array_02)
print(newArr)
newArr = np.multiply(array_01,array_02)
print(newArr)
newArr = np.divide(array_01,array_02)
print(newArr)
array_01 = np.array([1,2,3])
array_02 = np.array([2,2,2])
newArr = np.power(array_01,array_02)
print(newArr)

[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]


##소수점 정렬 
- 소수점을 정렬하는 다양한 방법


In [39]:
import numpy as np
temp_arr = np.trunc([-1,23,123])
print(temp_arr)

temp_arr = np.fix([-1.23,1.23])
print(temp_arr)

[ -1.  23. 123.]
[-1.  1.]


In [41]:
temp_arr = np.floor([-1.2124,1.24242])
print(temp_arr)

[-2.  1.]


In [42]:
temp_arr = np.ceil([-1.23123,1.23123])
print(temp_arr)

[-1.  2.]


## 조건식
- pandas
- numpy
- 조건식
  - 하나의 조건식
  - 다중 조건


In [44]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# 5보다 작으면 원 값 유지
# 5보다 크면 곱하기 10을 해주기

# np.where(조건식, 참일 때, 거짓일 때)
np.where (temp_arr<5, temp_arr, temp_arr * 10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [48]:
temp_arr = np.arange(10)
cond_list = [temp_arr > 5, temp_arr < 2]
choice_list = [temp_arr *2 , temp_arr +100]
# np.select(조건식 리스트, 결과값 리스트, default)
np.select(cond_list,choice_list,default=temp_arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])

## Reshape
- 배열의 차원 또는 크기를 바꾼다.
- 곱셈

In [50]:
import numpy as np
temp_array = np.ones((3,4))
print(temp_array.shape)
print(temp_array)

(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [54]:
after_reshape = temp_array.reshape(2,-1) #-1을 넣으면 알아서 계산해준다
# -1넣으면 알아서 계산해준다
print(after_reshape.shape)
print(after_reshape)

(2, 6)
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


def 함수이름(매개변수):
  return 반환값1, 반환값2

In [57]:
def add_sub(a,b):
  return a+b,a-b

x,y=add_sub(20,15)
print(x)
print(y)

35
5


In [60]:
def one_two():
  return [1,2]

x,y=one_two()
print(x)
print(y)
print(type(x))
print(type(y))

1
2
<class 'int'>
<class 'int'>


In [62]:
x=10
y=3
def get_quotient_remainder(x,y):
  return x//y,x%y

quotient, remainder = get_quotient_remainder(x,y)
print('몫 : {0}, 나머지: {1}'.format(quotient, remainder))

몫 : 3, 나머지: 1


## pandas 튜토리

In [64]:
import pandas as pd
print(pd.__version__)

1.3.5


In [67]:
temp_dict = {
    'col1': [1,2],
    'col2': [3,4]
}

df= pd.DataFrame(temp_dict)
print(df)
print(type(df))

   col1  col2
0     1     3
1     2     4
<class 'pandas.core.frame.DataFrame'>


In [69]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [75]:
DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/human_ai/Basic/Chapter 3. pandas/data/'
lemonade = pd.read_csv(DATA_PATH +'Lemonade2016.csv')
# covid_df = pd.read_csv(DATA_PATH +)

lemonade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Date         31 non-null     object 
 1   Location     32 non-null     object 
 2   Lemon        32 non-null     int64  
 3   Orange       32 non-null     int64  
 4   Temperature  32 non-null     int64  
 5   Leaflets     31 non-null     float64
 6   Price        32 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.9+ KB


In [77]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [79]:
s = pd.Series([1,3,5, np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [83]:
dates = pd.date_range('20220627', periods=6)
dates

DatetimeIndex(['2022-06-27', '2022-06-28', '2022-06-29', '2022-06-30',
               '2022-07-01', '2022-07-02'],
              dtype='datetime64[ns]', freq='D')

In [86]:
df = pd.DataFrame(np.random.randn(6,4), index =dates, columns = list('ABCD'))
df

A         B         C         D
2022-06-27 -0.187705  0.396903 -1.553965 -0.920126
2022-06-28 -0.540548  0.040966  0.018852  2.159429
2022-06-29  0.124971 -0.000083  0.941922  0.743876
2022-06-30  0.451639 -0.763349  0.825701  0.030078
2022-07-01 -0.299505 -0.354058 -0.696545  0.062945
2022-07-02 -0.607932 -0.133409  0.707404  1.150122

In [89]:
df2 = pd.DataFrame({'A':1.,
                    'B': pd.Timestamp('20220627'),
                    'C': pd.Series(1,index = list(range(4)),dtype='float32'),
                    'D': np.array([3] * 4, dtype = 'int32'),
                    'E': pd.Categorical(["test","train","test","train"]),
                    'F': 'foo'})
print(df2)
print(df2.dtypes)

     A          B    C  D      E    F
0  1.0 2022-06-27  1.0  3   test  foo
1  1.0 2022-06-27  1.0  3  train  foo
2  1.0 2022-06-27  1.0  3   test  foo
3  1.0 2022-06-27  1.0  3  train  foo
A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [91]:
df.tail(3)

A         B         C         D
2022-06-30  0.451639 -0.763349  0.825701  0.030078
2022-07-01 -0.299505 -0.354058 -0.696545  0.062945
2022-07-02 -0.607932 -0.133409  0.707404  1.150122

In [93]:
df.tail()

A         B         C         D
2022-06-28 -0.540548  0.040966  0.018852  2.159429
2022-06-29  0.124971 -0.000083  0.941922  0.743876
2022-06-30  0.451639 -0.763349  0.825701  0.030078
2022-07-01 -0.299505 -0.354058 -0.696545  0.062945
2022-07-02 -0.607932 -0.133409  0.707404  1.150122

In [95]:
df.head()

A         B         C         D
2022-06-27 -0.187705  0.396903 -1.553965 -0.920126
2022-06-28 -0.540548  0.040966  0.018852  2.159429
2022-06-29  0.124971 -0.000083  0.941922  0.743876
2022-06-30  0.451639 -0.763349  0.825701  0.030078
2022-07-01 -0.299505 -0.354058 -0.696545  0.062945